version: '3.7'

volumes:
  dependency-track:
  postgres-data:

services:
  dtrack-apiserver:
    image: dependencytrack/apiserver
    environment:
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://dtrack-db:5432/dtrack
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=admin
      - ALPINE_DATABASE_PASSWORD=admin
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - '8081:8080'
    volumes:
      - 'dependency-track:/data'
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=http://localhost:8081
    ports:
      - "8082:8080"
    restart: unless-stopped

  dtrack-db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dtrack
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pandoc:
    image: pandoc/latex
    volumes:
      - ./documents:/documents
    command: pandoc --version
    restart: unless-stopped
